---
- name: install packages
  hosts: all
  roles:
   - role: install_packages
     message: "installing packages"
   - role: deploy_docker
     message: "Deploying docker"
   - role: deploy_terraform
     message: "Deploying terraform"
   - role: copy_files
     message: "copying files to host"
   - role: git
     message: get git repos